/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Model.Person;
import Model.Address;
import Model.Contact;
import javax.swing.JOptionPane;


/**
 *
 * @author Dell
 */
public class MJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MJFrame
     */
    private Person person;
    
    public MJFrame() {
        initComponents();
        this.person= new Person();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        SetPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        fieldNUID = new javax.swing.JTextField();
        fieldFname = new javax.swing.JTextField();
        fieldLname = new javax.swing.JTextField();
        fieldCname = new javax.swing.JTextField();
        fieldPhone1 = new javax.swing.JTextField();
        fieldEmail1 = new javax.swing.JTextField();
        fieldWPhone = new javax.swing.JTextField();
        fieldWEmail = new javax.swing.JTextField();
        fieldCStName = new javax.swing.JTextField();
        fieldCAptNo = new javax.swing.JTextField();
        fieldCCity = new javax.swing.JTextField();
        fieldCZipcode = new javax.swing.JTextField();
        fieldPStName = new javax.swing.JTextField();
        fieldPAptNo = new javax.swing.JTextField();
        fieldPCity = new javax.swing.JTextField();
        fieldPZipcode = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        ViewPanel = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        viewnuid = new javax.swing.JLabel();
        viewfname = new javax.swing.JLabel();
        viewlname = new javax.swing.JLabel();
        viewcname = new javax.swing.JLabel();
        viewmobile1 = new javax.swing.JLabel();
        viewemail1 = new javax.swing.JLabel();
        viewwmobile = new javax.swing.JLabel();
        viewwemail = new javax.swing.JLabel();
        viewcstreet = new javax.swing.JLabel();
        viewcaptno = new javax.swing.JLabel();
        viewccity = new javax.swing.JLabel();
        viewczipcode = new javax.swing.JLabel();
        viewpstreet = new javax.swing.JLabel();
        viewpaptno = new javax.swing.JLabel();
        viewpcity = new javax.swing.JLabel();
        viewpzipcode = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();

        jLabel23.setText("jLabel23");

        jLabel24.setText("jLabel24");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SetPanel.setBackground(new java.awt.Color(204, 255, 153));

        jLabel1.setText("First Name");

        jLabel2.setText("Last Name");

        jLabel3.setText("NUID");

        jLabel5.setBackground(new java.awt.Color(204, 255, 204));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Personal Contact Info");

        jLabel6.setText("Phone");

        jLabel7.setText("Email");

        jLabel8.setBackground(new java.awt.Color(204, 255, 204));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Office Contact Info");

        jLabel9.setText("Phone");

        jLabel10.setText("Email");

        jLabel4.setBackground(new java.awt.Color(204, 255, 204));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Current Address");

        jLabel11.setText("Street Name");

        jLabel12.setText("Apt.No");

        jLabel13.setText("City");

        jLabel14.setText("Zipcode");

        jLabel15.setBackground(new java.awt.Color(204, 255, 204));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("Permanent Address");

        jLabel16.setText("Street Name");

        jLabel17.setText("City");

        jLabel18.setText("Apt.No");

        jLabel19.setText("Zipcode");

        jLabel20.setText("College Name");

        jLabel21.setBackground(new java.awt.Color(255, 255, 204));
        jLabel21.setFont(new java.awt.Font("Arial Black", 1, 16)); // NOI18N
        jLabel21.setText("STUDENT INFORMATION ");

        fieldNUID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNUIDActionPerformed(evt);
            }
        });

        fieldFname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldFnameActionPerformed(evt);
            }
        });

        fieldCZipcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCZipcodeActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SetPanelLayout = new javax.swing.GroupLayout(SetPanel);
        SetPanel.setLayout(SetPanelLayout);
        SetPanelLayout.setHorizontalGroup(
            SetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SetPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(SetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SetPanelLayout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(18, 18, 18)
                        .addComponent(fieldCname, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(231, 231, 231))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SetPanelLayout.createSequentialGroup()
                        .addGroup(SetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(SetPanelLayout.createSequentialGroup()
                                .addGroup(SetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(SetPanelLayout.createSequentialGroup()
                                        .addGroup(SetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel13))
                                        .addGroup(SetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(SetPanelLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(fieldCStName, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SetPanelLayout.createSequentialGroup()
                                                .addGap(12, 12, 12)
                                                .addComponent(fieldCCity, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(41, 41, 41))
                                    .addGroup(SetPanelLayout.createSequentialGroup()
                                        .addGroup(SetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(SetPanelLayout.createSequentialGroup()
                                                .addComponent(jLabel17)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(fieldPCity, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(SetPanelLayout.createSequentialGroup()
                                                .addComponent(jLabel16)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(fieldPStName, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(42, 42, 42)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(SetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SetPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(SetPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addGap(7, 7, 7)))
                                .addGroup(SetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fieldPZipcode, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fieldPAptNo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(SetPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(SetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(SetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fieldCAptNo, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fieldCZipcode, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, SetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, SetPanelLayout.createSequentialGroup()
                                .addGroup(SetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SetPanelLayout.createSequentialGroup()
                                        .addGap(130, 130, 130)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(SetPanelLayout.createSequentialGroup()
                                        .addGroup(SetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel9))
                                        .addGroup(SetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(SetPanelLayout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(fieldWPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(SetPanelLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(fieldPhone1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(49, 49, 49)
                                        .addGroup(SetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel7))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(SetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fieldEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fieldWEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SetPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(SetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SetPanelLayout.createSequentialGroup()
                        .addGroup(SetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addGroup(SetPanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(SetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fieldFname)
                                    .addComponent(fieldLname, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))))
                        .addGap(110, 110, 110))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SetPanelLayout.createSequentialGroup()
                        .addComponent(fieldNUID, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(231, 231, 231))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SetPanelLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(149, 149, 149))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SetPanelLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(180, 180, 180))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SetPanelLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(162, 162, 162))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SetPanelLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(188, 188, 188))))
        );
        SetPanelLayout.setVerticalGroup(
            SetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SetPanelLayout.createSequentialGroup()
                .addComponent(jLabel21)
                .addGap(6, 6, 6)
                .addGroup(SetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(fieldNUID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fieldFname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fieldLname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(fieldCname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(1, 1, 1)
                .addGroup(SetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(fieldPhone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(fieldWPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldWEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(fieldCStName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldCAptNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(fieldCCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldCZipcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel18)
                    .addComponent(fieldPStName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldPAptNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel19)
                    .addComponent(fieldPCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldPZipcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(SetPanel);

        ViewPanel.setBackground(new java.awt.Color(51, 51, 51));
        ViewPanel.setForeground(new java.awt.Color(255, 255, 255));

        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("NUID");

        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("First Name");

        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Last Name");

        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("College Name");

        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Personal Mobile No");

        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Personal Email");

        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Work Mobile No");

        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Work Email");

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("CURRENT ADDRESS");

        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Street");

        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Apt No");

        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("City");

        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Zipcode");

        jLabel35.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("PERMANENT ADDRESS");

        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Street");

        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("Apt No");

        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("City");

        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("Zipcode");

        jLabel42.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 51, 51));
        jLabel42.setText("HUSKY CARD");

        viewnuid.setForeground(new java.awt.Color(255, 255, 255));
        viewnuid.setText(" ");

        viewfname.setForeground(new java.awt.Color(255, 255, 255));
        viewfname.setText(" ");

        viewlname.setForeground(new java.awt.Color(255, 255, 255));
        viewlname.setText(" ");

        viewcname.setForeground(new java.awt.Color(255, 255, 255));
        viewcname.setText(" ");

        viewmobile1.setForeground(new java.awt.Color(255, 255, 255));
        viewmobile1.setText(" ");

        viewemail1.setForeground(new java.awt.Color(255, 255, 255));
        viewemail1.setText(" ");

        viewwmobile.setForeground(new java.awt.Color(255, 255, 255));
        viewwmobile.setText(" ");

        viewwemail.setForeground(new java.awt.Color(255, 255, 255));
        viewwemail.setText(" ");

        viewcstreet.setForeground(new java.awt.Color(255, 255, 255));
        viewcstreet.setText(" ");

        viewcaptno.setForeground(new java.awt.Color(255, 255, 255));
        viewcaptno.setText(" ");

        viewccity.setForeground(new java.awt.Color(255, 255, 255));
        viewccity.setText(" ");

        viewczipcode.setForeground(new java.awt.Color(255, 255, 255));
        viewczipcode.setText(" ");

        viewpstreet.setForeground(new java.awt.Color(255, 255, 255));
        viewpstreet.setText(" ");

        viewpaptno.setForeground(new java.awt.Color(255, 255, 255));
        viewpaptno.setText(" ");

        viewpcity.setForeground(new java.awt.Color(255, 255, 255));
        viewpcity.setText(" ");

        viewpzipcode.setForeground(new java.awt.Color(255, 255, 255));
        viewpzipcode.setText(" ");

        jLabel59.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(255, 255, 255));
        jLabel59.setText("CONTACT ");

        javax.swing.GroupLayout ViewPanelLayout = new javax.swing.GroupLayout(ViewPanel);
        ViewPanel.setLayout(ViewPanelLayout);
        ViewPanelLayout.setHorizontalGroup(
            ViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(ViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ViewPanelLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(ViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ViewPanelLayout.createSequentialGroup()
                                .addGroup(ViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel40, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel41, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(493, 493, 493))
                            .addGroup(ViewPanelLayout.createSequentialGroup()
                                .addGroup(ViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel28)
                                    .addComponent(jLabel29)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel25))
                                .addGap(18, 18, 18)
                                .addGroup(ViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(viewwmobile)
                                    .addComponent(viewwemail)
                                    .addComponent(viewnuid, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                                    .addComponent(viewlname)
                                    .addComponent(viewfname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(viewcname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(ViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabel27))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(ViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(viewemail1, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                                    .addComponent(viewmobile1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(ViewPanelLayout.createSequentialGroup()
                        .addGroup(ViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(ViewPanelLayout.createSequentialGroup()
                                .addComponent(jLabel31)
                                .addGap(42, 42, 42)
                                .addComponent(viewcstreet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(ViewPanelLayout.createSequentialGroup()
                                .addGroup(ViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel32)
                                    .addComponent(jLabel36)
                                    .addComponent(jLabel37))
                                .addGap(34, 34, 34)
                                .addGroup(ViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(ViewPanelLayout.createSequentialGroup()
                                        .addComponent(viewpaptno, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                                        .addGap(9, 9, 9))
                                    .addComponent(viewpstreet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(viewcaptno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGroup(ViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ViewPanelLayout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addGroup(ViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ViewPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel34)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(viewczipcode, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(ViewPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel33)
                                        .addGap(34, 34, 34)
                                        .addComponent(viewccity, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(ViewPanelLayout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addGroup(ViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel39)
                                    .addComponent(jLabel38))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(ViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(viewpcity)
                                    .addComponent(viewpzipcode, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())))
            .addGroup(ViewPanelLayout.createSequentialGroup()
                .addGroup(ViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ViewPanelLayout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addGroup(ViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel35)
                            .addComponent(jLabel30)))
                    .addGroup(ViewPanelLayout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jLabel42))
                    .addGroup(ViewPanelLayout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jLabel59)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        ViewPanelLayout.setVerticalGroup(
            ViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel42)
                .addGap(18, 18, 18)
                .addGroup(ViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewnuid)
                    .addComponent(jLabel40))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewfname)
                    .addComponent(jLabel41))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewlname)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewcname, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jLabel59)
                .addGap(18, 18, 18)
                .addGroup(ViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(viewwmobile)
                    .addComponent(jLabel26)
                    .addComponent(viewmobile1))
                .addGap(6, 6, 6)
                .addGroup(ViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(viewwemail)
                    .addComponent(jLabel27)
                    .addComponent(viewemail1))
                .addGap(18, 18, 18)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(viewcstreet)
                    .addComponent(jLabel33)
                    .addComponent(viewccity))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(viewcaptno)
                    .addComponent(jLabel34)
                    .addComponent(viewczipcode))
                .addGap(18, 18, 18)
                .addComponent(jLabel35)
                .addGap(18, 18, 18)
                .addGroup(ViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(viewpstreet)
                    .addComponent(jLabel38)
                    .addComponent(viewpcity))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(viewpaptno)
                    .addComponent(jLabel39)
                    .addComponent(viewpzipcode))
                .addGap(241, 241, 241))
        );

        jSplitPane1.setRightComponent(ViewPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldNUIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNUIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNUIDActionPerformed

    private void fieldFnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldFnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldFnameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String nuid = fieldNUID.getText();
        String first_name = fieldFname.getText();
        String last_name = fieldLname.getText();
        String college_name = fieldCname.getText();
        String p_mobile = fieldPhone1.getText();
        String p_email = fieldEmail1.getText();
        String w_mobile = fieldWPhone.getText();
        String w_email = fieldWEmail.getText();
        String c_streetname = fieldCStName.getText();
        String c_aptno = fieldCAptNo.getText();
        String c_city = fieldCCity.getText();
        String c_zipcode = fieldCZipcode.getText();
        String p_streetname = fieldPStName.getText();
        String p_aptno = fieldPAptNo.getText();
        String p_city = fieldPCity.getText();
        String p_zipcode = fieldPZipcode.getText();
        
        this.person.setNuid(nuid);
        this.person.setFName(first_name);
        this.person.setLName(last_name);
        this.person.setCName(college_name);
        Contact cont=this.person.getCont();
        cont.setEmail1(p_email);
        cont.setPhone1(p_mobile);
        cont.setWEmail(w_email);
        cont.setWPhone(w_mobile);
        Address addr = this.person.getAddr();
        addr.setPStName(p_streetname);
        addr.setPAptNo(p_aptno);
        addr.setPCity(p_city);
        addr.setPZipcode(p_zipcode);
        addr.setCStName(c_streetname);
        addr.setCAptNo(c_aptno);
        addr.setCCity(c_city);
        addr.setCZipcode(c_zipcode);
        display();
        JOptionPane.showMessageDialog(null, "SAVED STUDENT's INFORMATION SUCCESSFULLY");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void fieldCZipcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCZipcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCZipcodeActionPerformed
      
        private void display(){
      viewnuid.setText(this.person.getNuid());
      viewfname.setText(this.person.getFName());
      viewlname.setText(this.person.getLName());
      viewcname.setText(this.person.getCName());
      viewmobile1.setText(this.person.getCont().getPhone1());
      viewemail1.setText(this.person.getCont().getEmail1());
      viewwmobile.setText(this.person.getCont().getWPhone());
      viewwemail.setText(this.person.getCont().getWEmail());
      viewpstreet.setText(this.person.getAddr().getPStName());
      viewpaptno.setText(this.person.getAddr().getPAptNo());
      viewpcity.setText(this.person.getAddr().getPCity());
      viewpzipcode.setText(this.person.getAddr().getPZipcode());
      viewcstreet.setText(this.person.getAddr().getCStName());
      viewcaptno.setText(this.person.getAddr().getCAptNo());
      viewccity.setText(this.person.getAddr().getCCity());
      viewczipcode.setText(this.person.getAddr().getCZipcode());
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel SetPanel;
    private javax.swing.JPanel ViewPanel;
    private javax.swing.JTextField fieldCAptNo;
    private javax.swing.JTextField fieldCCity;
    private javax.swing.JTextField fieldCStName;
    private javax.swing.JTextField fieldCZipcode;
    private javax.swing.JTextField fieldCname;
    private javax.swing.JTextField fieldEmail1;
    private javax.swing.JTextField fieldFname;
    private javax.swing.JTextField fieldLname;
    private javax.swing.JTextField fieldNUID;
    private javax.swing.JTextField fieldPAptNo;
    private javax.swing.JTextField fieldPCity;
    private javax.swing.JTextField fieldPStName;
    private javax.swing.JTextField fieldPZipcode;
    private javax.swing.JTextField fieldPhone1;
    private javax.swing.JTextField fieldWEmail;
    private javax.swing.JTextField fieldWPhone;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel viewcaptno;
    private javax.swing.JLabel viewccity;
    private javax.swing.JLabel viewcname;
    private javax.swing.JLabel viewcstreet;
    private javax.swing.JLabel viewczipcode;
    private javax.swing.JLabel viewemail1;
    private javax.swing.JLabel viewfname;
    private javax.swing.JLabel viewlname;
    private javax.swing.JLabel viewmobile1;
    private javax.swing.JLabel viewnuid;
    private javax.swing.JLabel viewpaptno;
    private javax.swing.JLabel viewpcity;
    private javax.swing.JLabel viewpstreet;
    private javax.swing.JLabel viewpzipcode;
    private javax.swing.JLabel viewwemail;
    private javax.swing.JLabel viewwmobile;
    // End of variables declaration//GEN-END:variables
}
