/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Application;
import Model.Medicine;
import Model.MedicineCatalog;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Dell
 */
public class CatalogJPanel extends javax.swing.JPanel {
private Application application;

    /**
     * Creates new form CatalogJPanel
     */

    DefaultTableModel medTableModel;
    public CatalogJPanel(Application application) {
        initComponents();
        
        this.application=application;
        this.medTableModel=(DefaultTableModel) medicineCatalog.getModel();
        
        displayMedicineCatalog();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        medicineCatalog = new javax.swing.JTable();
        fieldName = new javax.swing.JTextField();
        fieldDosage = new javax.swing.JTextField();
        AddBtn = new javax.swing.JButton();
        DeleteBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        medicineCatalog.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Dosage"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(medicineCatalog);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 43, 375, 275));

        fieldName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldNameFocusLost(evt);
            }
        });
        fieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNameActionPerformed(evt);
            }
        });
        add(fieldName, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 69, 109, 37));

        fieldDosage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldDosageActionPerformed(evt);
            }
        });
        add(fieldDosage, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 124, 109, 37));

        AddBtn.setText("ADD");
        AddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBtnActionPerformed(evt);
            }
        });
        add(AddBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 206, -1, -1));

        DeleteBtn.setText("DELETE");
        DeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtnActionPerformed(evt);
            }
        });
        add(DeleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(476, 336, -1, -1));

        jLabel1.setText("DOSAGE");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel2.setText("NAME");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void fieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNameActionPerformed

    private void fieldDosageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldDosageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldDosageActionPerformed

    private void AddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBtnActionPerformed
        // TODO add your handling code here:
        //adding medicine
        
        String name= fieldName.getText();
        String dosage = fieldDosage.getText();
        MedicineCatalog catalog = this.application.getCatalog();
        
        catalog.createMedicine(name, Double.valueOf(dosage));
        
        displayMedicineCatalog();
    }//GEN-LAST:event_AddBtnActionPerformed

    private void fieldNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldNameFocusLost
        // TODO add your handling code here:
        
        String name = fieldName.getText();
        
        Boolean isUnique = this.application.getCatalog().checkIfMedicineUnique(name);
        if(isUnique){
            
        }else{
            fieldName.setText("");
            JOptionPane.showMessageDialog(null,"Medicine already exists");
        }
    }//GEN-LAST:event_fieldNameFocusLost

    private void DeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBtnActionPerformed
        // TODO add your handling code here:
        
        int selectedRow = medicineCatalog.getSelectedRow();
        
        if(selectedRow >= 0){
            Medicine med = (Medicine) medicineCatalog.getValueAt(selectedRow, 0);
            
            this.application.getCatalog().removeMedicine(med.getMedicineName());
            
            displayMedicineCatalog();
            JOptionPane.showMessageDialog(null, "Succesfully Deleted the record");
        }else{
            JOptionPane.showMessageDialog(null, "Select the record to delete");
        }
    }//GEN-LAST:event_DeleteBtnActionPerformed

    
    public void displayMedicineCatalog(){
        //check if the catalog is not empty
        
        ArrayList<Medicine> medicines = this.application.getCatalog().getMedicineList();
        
        if(medicines.size()>0){
            //populate
            
            medTableModel.setRowCount(0);
            
            for(Medicine med: medicines){
                
                Object row[] = new Object[2];
                row[0]=med;
                row[1]=med.getDosage();
                
                medTableModel.addRow(row);
            }
        }else{
            
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBtn;
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JTextField fieldDosage;
    private javax.swing.JTextField fieldName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable medicineCatalog;
    // End of variables declaration//GEN-END:variables
}
